on: push
jobs:
  first-job:
    runs-on: windows-latest
    steps:
      - run: node --version
      - run: npm  --version 

on: pull_request
 jobs:
    second_job:
      runs-on: ubuntu-latest
      steps:
        - run: git --version

  